"""Reader for USBPcap captures (.pcapng from Wireshark on Windows).

Parses the minimum of the little-endian pcapng container (the only one
generated by the captures in `captures/win-captures/`) and the USBPcap
header of each Enhanced Packet Block, returning bulk transfers with payload.
USBPcap records each URB in submit and complete; the dataLength > 0 filter
keeps the copy carrying the data (submit for OUT, complete for IN).
"""

from __future__ import annotations

import struct
from dataclasses import dataclass
from pathlib import Path

SHB_TYPE = 0x0A0D0D0A
EPB_TYPE = 0x00000006
BYTE_ORDER_MAGIC_LE = 0x1A2B3C4D
TRANSFER_BULK = 3
_USBPCAP_FIXED_HEADER = 27


@dataclass
class BulkTransfer:
    """A bulk transfer with data, as recorded by USBPcap."""

    endpoint: int   # bEndpointAddress (bit 7 = IN)
    info: int       # bit 0: 1 = IRP completado (device->host)
    irp_id: int
    ts: int         # microsegundos (ts_high << 32 | ts_low del EPB)
    payload: bytes

    @property
    def is_in(self) -> bool:
        return bool(self.endpoint & 0x80)


def _iter_blocks(data: bytes):
    pos = 0
    while pos + 12 <= len(data):
        btype, blen = struct.unpack_from("<II", data, pos)
        if blen < 12 or blen % 4 or pos + blen > len(data):
            raise ValueError(f"corrupt pcapng block at offset {pos:#x}")
        yield btype, data[pos + 8 : pos + blen - 4]
        pos += blen


def parse_bulk_transfers(path: str | Path) -> list[BulkTransfer]:
    """Bulk transfers with payload from a USBPcap capture, in order."""
    data = Path(path).read_bytes()
    if len(data) < 12 or struct.unpack_from("<I", data)[0] != SHB_TYPE:
        raise ValueError(f"{path}: not a pcapng file")
    magic = struct.unpack_from("<I", data, 8)[0]
    if magic != BYTE_ORDER_MAGIC_LE:
        raise ValueError(f"{path}: unsupported byte-order magic: {magic:#x}")

    transfers: list[BulkTransfer] = []
    for btype, body in _iter_blocks(data):
        if btype != EPB_TYPE:
            continue
        _, ts_hi, ts_lo, cap_len, _ = struct.unpack_from("<IIIII", body)
        record = body[20 : 20 + cap_len]
        if len(record) < _USBPCAP_FIXED_HEADER:
            continue
        header_len = struct.unpack_from("<H", record)[0]
        info = record[16]
        endpoint = record[21]
        transfer = record[22]
        data_len = struct.unpack_from("<I", record, 23)[0]
        if transfer != TRANSFER_BULK or data_len == 0:
            continue
        payload = record[header_len : header_len + data_len]
        if len(payload) != data_len:
            continue  # URB truncated by snaplen: not usable for analysis
        irp_id = struct.unpack_from("<Q", record, 2)[0]
        transfers.append(BulkTransfer(
            endpoint=endpoint,
            info=info,
            irp_id=irp_id,
            ts=(ts_hi << 32) | ts_lo,
            payload=payload,
        ))
    return transfers
